"""Clean resume text: remove garbled chars/watermarks, format as simple HTML.

Does NOT rewrite or optimize text expression — only removes noise and adds
structural formatting (headings, lists) for readability.

Supports both plain text and markdown input. Markdown input gets light noise
cleaning (structure preserved) and native markdown→HTML conversion.
"""

import re

import markdown as _md_lib

# Regex for pymupdf4llm image/object placeholders like:
#   ==> picture [57 x 80] intentionally omitted <==
#   ==> figure [120 x 90] intentionally omitted <==
_IMAGE_PLACEHOLDER_RE = re.compile(
    r'==>\s*\w+\s*\[[^\]]*\]\s*(?:intentionally\s*)?omitted\s*<==',
    re.IGNORECASE,
)

# Regex for markdown image refs generated by pymupdf4llm (e.g. ![](img_001.png))
_MD_IMAGE_REF_RE = re.compile(r'!\[[^\]]*\]\([^\)]*\.(?:png|jpg|jpeg|gif|bmp|svg|webp)\)', re.IGNORECASE)

# Recognized Chinese resume section headers (exact match only, no fuzzy guessing)
SECTION_PATTERNS = [
    # Personal info
    r'^(个人资料|个人信息|基本信息|个人简介|个人概况|基本资料|个人信息表)$',
    # Self-assessment
    r'^(自我评价|自我介绍|自我描述|个人优势|核心竞争力|个人特质)$',
    # Job intent
    r'^(求职意向|求职目标|应聘岗位|期望职位|求职方向|职业目标)$',
    # Education
    r'^(教育背景|教育经历|教育|学历|学习经历|学历背景|学术背景|培训经历|专业培训)$',
    # Work experience
    r'^(工作经历|工作经验|工作履历|职业经历|从业经历|职业背景|工作背景)$',
    r'^(实习经历|实习经验|社会实践|社会经历|校园经历|在校经历)$',
    # Projects
    r'^(项目经验|项目经历|项目|主要项目|参与项目|项目案例|项目展示|核心项目|重点项目)$',
    # Skills
    r'^(技能|技能特长|专业技能|技术栈|技术能力|计算机能力|专业能力|核心能力)$',
    r'^(语言能力|外语能力|语言水平|英语水平|外语水平)$',
    r'^(办公技能|办公软件|计算机水平|IT技能|编程能力)$',
    # Certificates & awards
    r'^(证书|资格证书|资质证书|所获证书|专业证书|认证)$',
    r'^(获奖|荣誉|奖项|所获荣誉|获奖情况|荣誉证书|奖励)$',
    # Contact
    r'^(联系方式|联系信息|联系电话|邮箱|电子邮箱|手机|通讯地址)$',
    # Hobbies
    r'^(兴趣爱好|个人爱好|特长|兴趣|业余爱好)$',
    # Misc
    r'^(期望薪资|薪资要求|薪资期望|期望地点|工作地点|到岗时间|可到岗)$',
    r'^(社会活动|社团活动|志愿者|公益活动|义工)$',
    r'^(研究经历|科研经历|学术成果|论文|发表论文|专利)$',
    r'^(作品|作品集|作品展示|个人作品|代表作品)$',
    r'^(其他|补充|附加信息|其他信息|备注)$',
]

# Common English words (for distinguishing real English text from noise)
_COMMON_ENGLISH_WORDS = {
    'the', 'and', 'for', 'with', 'from', 'have', 'has', 'been', 'will', 'would',
    'should', 'could', 'can', 'may', 'this', 'that', 'they', 'them', 'their',
    'what', 'when', 'where', 'which', 'who', 'how', 'not', 'are', 'was', 'were',
    'had', 'did', 'does', 'been', 'also', 'more', 'most', 'some', 'any', 'all',
    'each', 'every', 'only', 'very', 'just', 'about', 'into', 'over', 'after',
    'before', 'between', 'under', 'above', 'below', 'through', 'during', 'team',
    'project', 'data', 'code', 'test', 'design', 'develop', 'manage', 'system',
    'service', 'software', 'application', 'business', 'platform', 'solution',
    'technology', 'product', 'process', 'quality', 'experience', 'skill',
    'engineer', 'manager', 'director', 'lead', 'senior', 'junior', 'years',
    'university', 'college', 'degree', 'master', 'bachelor', 'computer',
    'science', 'engineering', 'programming', 'language', 'english', 'chinese',
    'office', 'excel', 'word', 'powerpoint', 'photoshop', 'python', 'java',
    'javascript', 'react', 'vue', 'angular', 'node', 'docker', 'kubernetes',
    'aws', 'azure', 'google', 'microsoft', 'oracle', 'mysql', 'mongodb',
    'redis', 'kafka', 'spring', 'django', 'flask', 'linux', 'windows',
    'mobile', 'android', 'ios', 'cloud', 'security', 'network', 'database',
    'frontend', 'backend', 'fullstack', 'agile', 'scrum', 'devops', 'cicd',
    'rest', 'graphql', 'json', 'xml', 'html', 'css', 'typescript', 'golang',
    'rust', 'scala', 'ruby', 'php', 'swift', 'kotlin', 'objective',
    # Unix / Linux commands (common 2-3 letter terms that appear in resumes)
    'awk', 'sed', 'grep', 'git', 'ssh', 'vim', 'vi', 'top', 'ps', 'cp',
    'mv', 'rm', 'cd', 'ls', 'cat', 'df', 'du', 'wc', 'ln', 'su', 'gdb',
    'cc', 'gcc', 'npm', 'pip', 'gem', 'go', 'sql', 'sh', 'zsh', 'bash',
    'env', 'tee', 'cut', 'tr', 'od', 'ar', 'as', 'ld', 'yum', 'apt',
    'tar', 'zip', 'scp', 'ftp', 'curl', 'wget', 'dig', 'ping', 'nc',
    'chmod', 'chown', 'mkdir', 'find', 'xargs', 'sort', 'uniq', 'head',
    'tail', 'less', 'more', 'man', 'sudo', 'pwd', 'jobs', 'kill', 'nice',
    'time', 'stat', 'file', 'diff', 'gpg', 'make', 'perl', 'lua', 'rpm',
    'dpkg', 'bzip2', 'gzip', 'rsync', 'netstat', 'ifconfig', 'tcpdump',
    'nmap', 'iptables', 'chgrp', 'gunzip', 'base64', 'md5sum', 'sha1sum',
    # Common tech abbreviations
    'api', 'sdk', 'cli', 'gui', 'tui', 'ide', 'cdn', 'dns', 'tcp', 'udp',
    'vpn', 'lan', 'wan', 'nat', 'vm', 'cpu', 'gpu', 'ram', 'ssd', 'hdd',
    'crud', 'rest', 'rpc', 'xml', 'css', 'dom', 'svg', 'csv', 'mvc', 'mvp',
    'spa', 'ssr', 'ssg', 'jwt', 'tdd', 'bdd', 'ddd', 'orm', 'odm', 'cms',
    'crm', 'erp', 'scm', 'pr', 'mr', 'poc', 'mvp', 'kpi', 'sla', 'slo',
    'slb', 'ecs', 'ecr', 'eks', 'ec2', 's3', 'rds', 'vpc', 'iam', 'elb',
    'cdn', 'waf', 'ddos', 'gcp', 'oci', 'jvm', 'jdk', 'jre', 'jar', 'war',
    'ear', 'pom', 'npm', 'yarn', 'pnpm', 'npx', 'cli', 'sdk', 'api', 'rpc',
    'uri', 'url', 'urn', 'rss', 'atom', 'yaml', 'toml', 'ini', 'cfg', 'env',
    'pid', 'uid', 'gid', 'fd', 'io', 'os', 'db', 'ui', 'ux', 'dx',
}


def _ratio(line: str, pattern: str) -> float:
    """Ratio of characters matching pattern in the line."""
    t = len(line)
    if t == 0:
        return 0.0
    return len(re.findall(pattern, line)) / t


def _is_garbled_line(line: str) -> bool:
    """Check if a line is noise: watermark, encoding artifact, PDF junk."""
    stripped = line.strip()
    if not stripped:
        return False

    # Never discard lines containing email addresses
    if _contains_email(stripped):
        return False

    t = len(stripped)

    # Too short to be meaningful
    if t <= 1:
        return True

    # Single isolated Latin letter or digit — noise
    if re.match(r'^[a-zA-Z0-9]$', stripped):
        return True

    # Only symbols / punctuation
    if re.match(r'^[\W_]+$', stripped):
        return True

    # Contains control / non-printable characters
    if re.search(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]', stripped):
        return True

    # Count meaningful character types
    chinese = len(re.findall(r'[一-鿿㐀-䶿]', stripped))
    letters = len(re.findall(r'[a-zA-Z]', stripped))
    digits = len(re.findall(r'[0-9]', stripped))
    meaningful = chinese + letters + digits

    m_ratio = meaningful / t

    # Very low meaningful ratio → garbage
    if m_ratio < 0.2:
        return True

    # No Chinese characters at all
    if chinese == 0:
        # Lines that are just 1-4 isolated Latin letters/digits (no real words)
        # e.g. "Vj", "Qs Rn", "Xp Lm", "A B C"
        if t < 20 and letters <= 6 and letters >= 1:
            # Check if it contains any real English word
            words = re.findall(r'[a-zA-Z]{3,}', stripped.lower())
            real_words = [w for w in words if w in _COMMON_ENGLISH_WORDS]
            if not real_words and len(words) < 2:
                return True

        # Longer line with only Latin chars but no real English structure
        # (all caps short tokens = likely noise)
        if letters > 0 and t < 35:
            tokens = stripped.split()
            if all(len(tok) <= 3 for tok in tokens) and len(tokens) <= 3:
                return True

    # Mozibake (UTF-8 bytes rendered as Latin-1)
    if _ratio(stripped, r'[\xc2-\xf4][\x80-\xbf]') > 0.1:
        return True
    if len(re.findall(r'[ÃÂÄÅÆÇÈÉÊËÌÍÎÏ]', stripped)) >= 2:
        return True

    # PDF artifacts: long runs of same character
    for ch in set(stripped):
        if len(ch) == 1 and stripped.count(ch) > max(8, t * 0.6):
            return True

    # Lines that look like table separators
    if re.match(r'^[\-\=\_\|\+\s]+$', stripped) and len(stripped) > 4:
        return True

    # Very short line (1-3 chars) with no Chinese — almost certainly noise
    if t <= 3 and chinese == 0:
        return True

    # PDF watermark fragments: repeated short text
    if t < 10 and chinese == 0 and letters < 4 and digits == 0:
        return True

    return False


# Paired punctuation/bracket characters that should be preserved together
_PAIRED_PUNCT = {
    '(': ')', '（': '）', '【': '】', '「': '」', '《': '》', '〈': '〉',
    '"': '"', "'": "'", '“': '”', '‘': '’', '『': '』', '〔': '〕',
    '［': '］', '｛': '｝', '＜': '＞', '⁽': '⁾', '₍': '₎',
}
# Reverse mapping: closing → opening
_PAIRED_CLOSE_TO_OPEN = {v: k for k, v in _PAIRED_PUNCT.items()}


def _strip_boundary_punct(line: str) -> str:
    """Strip leading/trailing noise punctuation, keeping paired brackets/quotes intact.

    Only strips punctuation that is NOT part of a matched pair within the same line.
    For example, 「软件工程师」 keeps both brackets because they form a pair;
    but a dangling leading quote on "软件工程师 keeps only the content.
    """
    s = line.strip()
    if not s:
        return s

    # --- Strip from start ---
    while s:
        ch = s[0]
        if ch.isalnum() or '一' <= ch <= '鿿' or '㐀' <= ch <= '䶿':
            break
        # If it's an opener, check if its matching closer exists in the remainder
        if ch in _PAIRED_PUNCT:
            closer = _PAIRED_PUNCT[ch]
            if closer in s[1:]:
                break
        # If it's a closer at the start, check if its matching opener exists later
        if ch in _PAIRED_CLOSE_TO_OPEN:
            opener = _PAIRED_CLOSE_TO_OPEN[ch]
            if opener in s[1:]:
                break
        s = s[1:]

    # --- Strip from end ---
    while s:
        ch = s[-1]
        if ch.isalnum() or '一' <= ch <= '鿿' or '㐀' <= ch <= '䶿':
            break
        # If it's a closer at the end, check if its matching opener exists before it
        if ch in _PAIRED_CLOSE_TO_OPEN:
            opener = _PAIRED_CLOSE_TO_OPEN[ch]
            if opener in s[:-1]:
                break
        # If it's an opener at the end, check if its matching closer exists earlier
        if ch in _PAIRED_PUNCT:
            closer = _PAIRED_PUNCT[ch]
            if closer in s[:-1]:
                break
        s = s[:-1]

    return s


def _clean_line_noise(line: str) -> str:
    """Remove inline noise sequences from a line while preserving valid content."""

    # Extract and protect email addresses before cleaning
    emails = _EMAIL_RE.findall(line)
    for i, email in enumerate(emails):
        line = line.replace(email, f'__EMAIL_{i}__')

    # Remove mojibake sequences (UTF-8 continuation bytes rendered as Latin-1)
    line = re.sub(r'[\xc2-\xf4][\x80-\xbf]{1,2}', '', line)

    # Remove long hash/ID tokens (>20 alphanumeric chars with mixed case/digits)
    line = re.sub(r'\b[a-zA-Z0-9_-]{20,}\b', '', line)

    # Remove UUID patterns
    line = re.sub(r'\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b', '', line)

    # Remove isolated 1-2 letter tokens that aren't real English words
    def _filter_token(m):
        tok = m.group(0)
        if tok.lower() in _COMMON_ENGLISH_WORDS:
            return tok
        if re.match(r'^[A-Z]{2,5}$', tok):
            return tok
        if len(tok) >= 4 and tok.isalpha():
            return tok
        return ''

    line = re.sub(r'\b[a-zA-Z]{1,3}\b', _filter_token, line)

    # Remove dangling punctuation and repeated symbols
    line = re.sub(r'[\•\*\▪\▸\⚫\⦁\⚬\✓\✔\☑]{2,}', '', line)
    line = re.sub(r'[|]{2,}', '', line)

    # Collapse whitespace
    line = re.sub(r'\s+', ' ', line)

    # Restore email addresses BEFORE boundary punctuation stripping,
    # so the placeholders cannot be corrupted by [\W_]+ patterns.
    for i, email in enumerate(emails):
        line = line.replace(f'__EMAIL_{i}__', email)

    # Remove leading/trailing noise punctuation, preserving paired brackets/quotes
    line = _strip_boundary_punct(line)

    return line


def _is_section_header(line: str) -> bool:
    """Check if a line is a recognized resume section header.

    Only matches against known section patterns — no fuzzy heuristic.
    Random short Chinese lines from PDF extraction artifacts must NOT be
    treated as section headers.
    """
    stripped = line.strip()
    if not stripped or len(stripped) > 30:
        return False

    for pattern in SECTION_PATTERNS:
        if re.match(pattern, stripped):
            return True

    return False


def _is_hash_or_id_string(line: str) -> bool:
    """Detect meaningless hash/ID/tracking strings from PDF metadata.

    Examples:
      - da5d56a498ad32a61HB-2tS7FVRSwY62V_qeWOGgmvbRNBRq1w
      - a1b2c3d4-e5f6-7890-abcd-ef1234567890
      - 550e8400-e29b-41d4-a716-446655440000
    """
    stripped = line.strip()
    t = len(stripped)

    # Very long alphanumeric string with mixed case + digits + symbols
    if t >= 20:
        alnum = len(re.findall(r'[a-zA-Z0-9]', stripped))
        if alnum / t > 0.7:
            # Check if it looks random (not a URL, not an email, not a file path)
            if not re.match(r'^https?://', stripped) and '@' not in stripped:
                # Count transitions between char types as indicator of randomness
                transitions = len(re.findall(r'[a-z][A-Z]|[A-Z][a-z]|[a-zA-Z][0-9]|[0-9][a-zA-Z]', stripped))
                # Random strings have many case/digit transitions
                if transitions >= 3 or '_' in stripped or '-' in stripped:
                    return True

    # UUID pattern
    if re.match(r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$', stripped):
        return True

    # Long hex string (>16 hex chars, no spaces)
    if t >= 16 and re.match(r'^[0-9a-fA-F]+$', stripped):
        return True

    return False


# Email pattern for protection
_EMAIL_RE = re.compile(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}')


def _contains_email(line: str) -> bool:
    """Check if line contains an email address that must be preserved."""
    return bool(_EMAIL_RE.search(line))


def _is_sentence_end(line: str) -> bool:
    """Check if a line ends with sentence-ending punctuation."""
    return bool(re.search(r'[。！？…\.\!\?；;]$', line.rstrip()))


def _is_list_item(line: str) -> bool:
    """Check if line is a list item (bullet, numbered, or lettered)."""
    stripped = line.strip()
    # Bullet chars: - • * ▪ ▸ ◆ ► ➢ · – — ★ ✓ ✔ ☑ ☐ ■ □ ○ ● ◉
    if re.match(r'^[\-\•\*\▪\▸\⚫\⦁\⚬\✓\✔\☑\◆\►\➢\·\–\—\★\✓\✔\☑\☐\■\□\○\●\◉]\s', stripped):
        return True
    # Numbered: 1. 1) 1、 (1) ①
    if re.match(r'^\d+[\.\)\)、]\s', stripped):
        return True
    if re.match(r'^[\(（]\d+[\)）]\s', stripped):
        return True
    if re.match(r'^[①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳]', stripped):
        return True
    # Chinese numbered: 一、二、三、
    if re.match(r'^[一二三四五六七八九十]+[、，,]\s', stripped):
        return True
    # Lettered: a) A. (a)
    if re.match(r'^[a-zA-Z][\.\)]\s', stripped):
        return True
    return False


def _is_sub_item_start(line: str) -> bool:
    """Check if a line starts a new sub-item that should stand alone.

    These are common resume patterns for work responsibilities, project roles, etc.
    """
    stripped = line.strip()
    # Lines starting with common Chinese action verbs (work/project items)
    action_verbs = r'^(负责|参与|主导|担任|承担|从事|独立|协助|配合|推动|组织|管理|设计|开发|实现|搭建|构建|重构|优化|改进|提升|完成|制定|撰写|编写|梳理|分析|调研|研究|测试|部署|维护|运维|支持|对接|沟通|协调|汇报|带领|指导|培训|建立|建立|引入|落地|推广|执行|策划|统筹|把控|监控|审核|评估|输出|交付|上线|迭代)'
    if re.match(action_verbs, stripped):
        return True
    # Lines starting with project/company/role names followed by separator
    # e.g. "项目名称：XXX", "公司名称：XXX", "岗位：XXX"
    if re.match(r'^(项目|公司|客户|产品|平台|系统|工具|框架|组件|模块|服务|应用|APP|APP|Web|H5|小程序|公众号)[\s\:：\-\—]+', stripped):
        return True
    # Lines starting with role/title patterns
    if re.match(r'^(高级|资深|初级|实习)?(前端|后端|全栈|算法|数据|测试|运维|产品|UI|UX|Android|iOS|Java|Python|Go|C\+\+|PHP|Node\.js|React|Vue|Angular)\s*(工程师|开发|经理|专家|架构师|负责人|组长|总监)', stripped):
        return True
    return False


def _is_date_start(line: str) -> bool:
    """Check if line starts with a date range (common resume pattern).

    Matches:
      - 2023.03-至今 / 2023年3月-至今 / 2023/03-现在
      - 2020.01-2023.06 / 2020年1月-2023年6月
    """
    return bool(re.match(
        r'^\d{4}[\.\-\/年]\d{1,2}[月]?\s*[\-\–—至到]\s*(\d{4}[\.\-\/年]\d{1,2}[月]?|至今|现在)',
        line,
    ))


def _merge_broken_paragraphs(lines: list[str]) -> list[str]:
    """Merge lines broken by PDF extraction, but preserve intentional structure.

    Merging rules (ALL must be true to merge):
    1. Current line doesn't end with sentence-ending punctuation
    2. Next line exists and is not empty
    3. Neither line is a header, list item, date start, or sub-item start
    4. Current line is short (< 30 chars) — long lines stand alone
    5. Current merged buffer hasn't exceeded reasonable paragraph size
    """
    if not lines:
        return lines

    result = []
    buffer = ''

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Empty line: flush buffer
        if not stripped:
            if buffer:
                result.append(buffer)
                buffer = ''
            result.append('')
            continue

        # Never merge these: headers, list items, date starts, sub-item starts
        is_break = (
            _is_section_header(stripped) or
            _is_list_item(stripped) or
            _is_date_start(stripped) or
            _is_sub_item_start(stripped)
        )

        if is_break:
            if buffer:
                result.append(buffer)
                buffer = ''
            result.append(stripped)
            continue

        # Is there a next line to potentially merge with?
        has_next = i + 1 < len(lines)
        next_line = lines[i + 1].strip() if has_next else ''
        next_is_break = (
            _is_section_header(next_line) or
            _is_list_item(next_line) or
            _is_date_start(next_line) or
            _is_sub_item_start(next_line)
        ) if has_next else True

        # Decide whether to merge
        should_merge = (
            has_next and
            next_line and  # Next line not empty
            not _is_sentence_end(stripped) and  # Doesn't end sentence
            not next_is_break and  # Next isn't a structural break
            len(stripped) < 30 and  # Current line is short (likely broken)
            len(buffer + stripped) < 120  # Don't make paragraphs too long
        )

        if buffer:
            if should_merge:
                buffer += stripped
            else:
                buffer += stripped
                result.append(buffer)
                buffer = ''
        else:
            if should_merge:
                buffer = stripped
            else:
                result.append(stripped)

    if buffer:
        result.append(buffer)

    return result


def _remove_hidden_data_fragments(lines: list[str]) -> list[str]:
    """Remove isolated short fragments that are likely PDF hidden/embedded data.

    Some PDF providers embed DRM watermarks or tracking data as hidden text.
    When extracted, these appear as short isolated lines that don't connect
    to surrounding resume content.

    Also removes dangling section-number-like fragments (e.g. "3.", "IV.")
    that aren't part of real content.
    """
    if len(lines) < 3:
        return lines

    result = []
    first_content_line = True  # Protect first non-empty line (often the name)
    for i, line in enumerate(lines):
        stripped = line.strip()

        # Keep empty lines
        if not stripped:
            result.append(line)
            continue

        # Never remove lines containing email addresses
        if _contains_email(stripped):
            first_content_line = False
            result.append(line)
            continue

        # Keep recognized section headers
        if _is_section_header(stripped):
            first_content_line = False
            result.append(line)
            continue

        # Keep list items
        if _is_list_item(stripped):
            first_content_line = False
            result.append(line)
            continue

        # Check if this is an isolated short fragment
        t = len(stripped)
        if t <= 6 and not first_content_line:
            prev_empty = i == 0 or not lines[i - 1].strip()
            next_empty = i == len(lines) - 1 or not lines[i + 1].strip()

            # Isolated between empty lines → likely hidden data fragment
            if prev_empty and next_empty:
                continue

            # Isolated before/after a section header → likely artifact
            if prev_empty and i + 1 < len(lines) and _is_section_header(lines[i + 1].strip()):
                continue
            if next_empty and i > 0 and _is_section_header(lines[i - 1].strip()):
                continue

        # Remove lines that look like dangling section numbers
        # e.g. "3.", "IV.", "(2)", "三、"
        # Never remove the first content line (likely a name)
        if re.match(r'^[\dIVXivx]+[\.\)、）]?$', stripped) and t <= 5 and not first_content_line:
            prev_empty = i == 0 or not lines[i - 1].strip()
            next_empty = i == len(lines) - 1 or not lines[i + 1].strip()
            if prev_empty and next_empty:
                continue

        first_content_line = False
        result.append(line)

    return result


def _is_markdown(text: str) -> bool:
    """Detect if text is markdown by looking for structural markers."""
    lines = text.split('\n')
    md_lines = 0
    for line in lines[:50]:  # Sample first 50 lines
        stripped = line.strip()
        if not stripped:
            continue
        if re.match(r'^#{1,6}\s', stripped):  # Headers
            md_lines += 1
        elif re.match(r'^[\-\*\+]\s', stripped):  # Unordered lists
            md_lines += 1
        elif re.match(r'^\*\*.*\*\*', stripped):  # Bold
            md_lines += 1
        elif re.match(r'^\|.+\|', stripped):  # Tables
            md_lines += 1
    return md_lines >= 2


def _clean_markdown(text: str) -> str:
    """Light cleaning for markdown: remove garbled lines and noise, preserve structure."""
    if not text:
        return ""

    lines = text.split('\n')
    cleaned = []

    for line in lines:
        stripped = line.strip()

        # Preserve empty lines (markdown uses them for paragraph breaks)
        if not stripped:
            cleaned.append('')
            continue

        # Remove whole-line hash/ID strings (PDF metadata)
        if _is_hash_or_id_string(stripped):
            continue

        # Remove image/object placeholders from pymupdf4llm
        if _IMAGE_PLACEHOLDER_RE.search(stripped):
            continue

        # Remove lines that are just a markdown image ref
        if _MD_IMAGE_REF_RE.match(stripped):
            continue

        # Remove garbled lines
        if _is_garbled_line(stripped):
            continue

        # Light inline noise cleaning (but preserve markdown syntax)
        cleaned_line = _clean_line_noise_markdown(stripped)
        if cleaned_line:
            cleaned.append(cleaned_line)

    # Collapse multiple consecutive empty lines
    collapsed = []
    prev_empty = False
    for line in cleaned:
        if line == '':
            if not prev_empty:
                collapsed.append(line)
                prev_empty = True
        else:
            collapsed.append(line)
            prev_empty = False

    return '\n'.join(collapsed).strip()


def _clean_line_noise_markdown(line: str) -> str:
    """Clean inline noise from a markdown line, preserving markdown syntax.

    Less aggressive than _clean_line_noise — only removes things that are
    definitely garbage, never touches markdown formatting.
    """
    # Protect email addresses
    emails = _EMAIL_RE.findall(line)
    for i, email in enumerate(emails):
        line = line.replace(email, f'__EMAIL_{i}__')

    # Remove mojibake sequences
    line = re.sub(r'[\xc2-\xf4][\x80-\xbf]{1,2}', '', line)

    # Remove UUID patterns
    line = re.sub(r'\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b', '', line)

    # Remove long hash tokens (>30 chars, mixed case/digits/hyphens)
    line = re.sub(r'\b[a-zA-Z0-9_-]{30,}\b', '', line)

    # Remove inline image placeholders and markdown image refs
    line = _IMAGE_PLACEHOLDER_RE.sub('', line)
    line = _MD_IMAGE_REF_RE.sub('', line)

    # Collapse whitespace (but not newlines)
    line = re.sub(r'[^\S\n]+', ' ', line)

    # Restore emails
    for i, email in enumerate(emails):
        line = line.replace(f'__EMAIL_{i}__', email)

    return line.strip()


def clean_resume_text(text: str) -> str:
    """Clean resume text: remove garbled lines, inline noise.

    Routes to appropriate cleaner based on whether input is markdown or plain text.
    """
    if not text:
        return ""

    if _is_markdown(text):
        return _clean_markdown(text)

    # === Plain text path (original logic) ===
    lines = text.split('\n')
    cleaned_lines = []

    for line in lines:
        stripped = line.strip()

        if not stripped:
            cleaned_lines.append('')
            continue

        # Remove whole-line hash/ID strings
        if _is_hash_or_id_string(stripped):
            continue

        if _is_garbled_line(stripped):
            continue

        cleaned = _clean_line_noise(stripped)
        if not cleaned:
            continue
        cleaned_lines.append(cleaned)

    # Collapse multiple consecutive empty lines into at most one
    collapsed = []
    prev_empty = False
    for line in cleaned_lines:
        if line == '':
            if not prev_empty:
                collapsed.append(line)
                prev_empty = True
        else:
            collapsed.append(line)
            prev_empty = False

    # Remove isolated fragments from PDF hidden data
    cleaned = _remove_hidden_data_fragments(collapsed)

    return '\n'.join(cleaned).strip()


def _markdown_to_html(md_text: str) -> str:
    """Convert markdown to styled HTML for resume display.

    Uses python-markdown with extensions for tables and fenced code,
    then wraps in resume-specific CSS classes.
    """
    html = _md_lib.markdown(
        md_text,
        extensions=['tables', 'fenced_code'],
    )
    # Wrap in a container div for resume-specific styling
    return f'<div class="resume-md">{html}</div>'


def resume_to_html(text: str) -> str:
    """Convert resume text to HTML for display.

    Uses markdown→HTML conversion for markdown input,
    custom heuristics for plain text.
    """
    if not text:
        return '<p class="empty-text">无内容</p>'

    cleaned = clean_resume_text(text)
    if not cleaned:
        return '<p class="empty-text">无内容</p>'

    if _is_markdown(cleaned):
        return _markdown_to_html(cleaned)

    lines = cleaned.split('\n')
    html_parts = []
    in_list = False
    in_para = False

    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if not line:
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            if in_para:
                html_parts.append('</p>')
                in_para = False
            i += 1
            continue

        # Section header detection
        if _is_section_header(line):
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            if in_para:
                html_parts.append('</p>')
                in_para = False
            html_parts.append(f'<h3 class="resume-section">{_escape_html(line)}</h3>')
            i += 1
            continue

        # List item detection
        list_match = re.match(r'^[\-\•\*\▪\▸\⚫\⦁\⚬\✓\✔\☑]\s+(.+)', line)
        if list_match:
            if not in_list:
                html_parts.append('<ul class="resume-list">')
                in_list = True
            html_parts.append(f'<li>{_format_inline(_escape_html(list_match.group(1)))}</li>')
            i += 1
            continue

        # Numbered list
        num_match = re.match(r'^(\d+[\.\)、])\s*(.+)', line)
        if num_match:
            if not in_list:
                html_parts.append('<ul class="resume-list">')
                in_list = True
            html_parts.append(f'<li>{_format_inline(_escape_html(num_match.group(2)))}</li>')
            i += 1
            continue

        # Date range line (e.g. "2023.03-至今", "2020.01-2023.06")
        date_match = re.match(
            r'^(\d{4}[\.\-\/年]\d{1,2}[月]?\s*[\-\–—至到]\s*(\d{4}[\.\-\/年]\d{1,2}[月]?|至今|现在))(.*)',
            line,
        )
        if date_match:
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            if not in_para:
                html_parts.append('<p class="resume-para">')
                in_para = True
            formatted = (
                f'<span class="resume-date">{_escape_html(date_match.group(1))}</span>'
                f'{_format_inline(_escape_html(date_match.group(2)))}'
            )
            html_parts.append(formatted)
            i += 1
            continue

        # Regular paragraph
        if in_list:
            html_parts.append('</ul>')
            in_list = False
        if not in_para:
            html_parts.append('<p class="resume-para">')
            in_para = True
        else:
            html_parts.append('<br>')
        html_parts.append(_format_inline(_escape_html(line)))
        i += 1

    if in_list:
        html_parts.append('</ul>')
    if in_para:
        html_parts.append('</p>')

    return '\n'.join(html_parts)


# Recognized JD section headers for formatting
_JD_SECTION_PATTERNS = [
    # Responsibilities
    r'^(岗位职责|工作职责|职责描述|主要职责|职位职责|岗位描述|工作内容|工作描述|职位描述|职责范围)$',
    # Requirements
    r'^(任职要求|岗位要求|职位要求|招聘要求|能力要求|技能要求|我们希望你|你需要具备|我们需要你)$',
    r'^(基本要求|基础要求|必备条件|硬性要求)$',
    # Bonus / preferred
    r'^(加分项|优先条件|优先考虑|加分条件|优先条件|额外加分|有以下经验者优先)$',
    r'^(优先录用|优先|我们希望|理想人选|期待你|期望你)$',
    # Compensation & benefits
    r'^(我们提供|薪资福利|福利待遇|薪酬福利|薪资待遇|我们能提供|你将获得)$',
    r'^(工作时间|工作地点|工作地址|公司地址|办公地点)$',
    # Company / team
    r'^(关于我们|公司介绍|团队介绍|公司简介|团队简介|业务介绍)$',
    # Contact / apply
    r'^(联系方式|应聘方式|投递方式|申请方式|如何申请)$',
    # Others
    r'^(晋升空间|发展前景|职业发展|成长空间|培训体系)$',
    r'^(面试流程|招聘流程|面试安排)$',
    r'^(备注|其他|补充说明|其他说明)$',
]


def _is_jd_section_header(line: str) -> bool:
    """Check if a line is a JD section header."""
    stripped = line.strip()
    if not stripped or len(stripped) > 30:
        return False
    for pattern in _JD_SECTION_PATTERNS:
        if re.match(pattern, stripped):
            return True
    return False


def jd_to_html(text: str) -> str:
    """Convert JD text to formatted HTML for display.

    Unlike resume_to_html, this does NOT clean noise (JD is user-written).
    It only adds structural formatting: section headers, lists, paragraphs.
    """
    if not text:
        return '<p class="empty-text">无内容</p>'

    lines = text.strip().split('\n')
    html_parts = []
    in_list = False
    in_para = False

    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if not line:
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            if in_para:
                html_parts.append('</p>')
                in_para = False
            i += 1
            continue

        # JD section header detection
        if _is_jd_section_header(line):
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            if in_para:
                html_parts.append('</p>')
                in_para = False
            html_parts.append(f'<h3 class="resume-section jd-section">{_escape_html(line)}</h3>')
            i += 1
            continue

        # Also check resume section patterns (may overlap with JD)
        if _is_section_header(line):
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            if in_para:
                html_parts.append('</p>')
                in_para = False
            html_parts.append(f'<h3 class="resume-section jd-section">{_escape_html(line)}</h3>')
            i += 1
            continue

        # List item detection
        list_match = re.match(r'^[\-\•\*\▪\▸\⚫\⦁\⚬\✓\✔\☑]\s+(.+)', line)
        if list_match:
            if not in_list:
                html_parts.append('<ul class="resume-list jd-list">')
                in_list = True
            html_parts.append(f'<li>{_format_inline(_escape_html(list_match.group(1)))}</li>')
            i += 1
            continue

        # Numbered list: "1. xxx", "1、xxx", "(1) xxx"
        num_match = re.match(r'^(\d+[\.\)、])\s*(.+)', line)
        if num_match:
            if not in_list:
                html_parts.append('<ul class="resume-list jd-list">')
                in_list = True
            html_parts.append(f'<li>{_format_inline(_escape_html(num_match.group(2)))}</li>')
            i += 1
            continue

        # Chinese numbered list: "1、xxx"
        cn_num = re.match(r'^[（(]?(\d+)[）)]?\s*[、，,]\s*(.+)', line)
        if cn_num:
            if not in_list:
                html_parts.append('<ul class="resume-list jd-list">')
                in_list = True
            html_parts.append(f'<li>{_format_inline(_escape_html(cn_num.group(2)))}</li>')
            i += 1
            continue

        # Lines that look like requirement items: "· 本科以上学历" or "• 3年以上经验"
        req_match = re.match(r'^[·•●◎◆►▸]\s*(.+)', line)
        if req_match:
            if not in_list:
                html_parts.append('<ul class="resume-list jd-list">')
                in_list = True
            html_parts.append(f'<li>{_format_inline(_escape_html(req_match.group(1)))}</li>')
            i += 1
            continue

        # Regular paragraph
        if in_list:
            html_parts.append('</ul>')
            in_list = False
        if not in_para:
            html_parts.append('<p class="resume-para jd-para">')
            in_para = True
        else:
            html_parts.append('<br>')
        html_parts.append(_format_inline(_escape_html(line)))
        i += 1

    if in_list:
        html_parts.append('</ul>')
    if in_para:
        html_parts.append('</p>')

    return '\n'.join(html_parts)


def _escape_html(text: str) -> str:
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')


def _format_inline(text: str) -> str:
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    return text


# ── LLM markdown restructuring ──────────────────────────────────────────────

_RESTRUCTURE_SYSTEM_PROMPT = """你是一位专业的简历排版专家。你的任务是将从PDF提取的原始简历内容整理成结构清晰、层次分明的Markdown格式。

核心要求：
1. **保留所有原始信息**，不要删减或改写候选人的实际经历内容
2. 使用合适的标题层级组织简历结构：
   - `## 姓名` 或 `## 个人信息`
   - `### 教育背景`、`### 工作经历`、`### 项目经验`、`### 技能特长` 等
3. 将散乱的文本块组织成清晰的**列表**（用 `- `）和段落
4. 工作经历和项目经验中，每条经历使用 `**公司/项目名** | 时间范围` 格式
5. 统一日期格式为 `YYYY.MM`
6. **只删除**：明显的水印字符、页眉页脚页码、PDF提取产生的乱码、无意义的随机字符序列
7. 保持技能、证书、联系方式等关键信息的完整性
8. 如果原文是中文简历，输出也应是中文标题

直接输出整理后的Markdown，不要添加任何解释性文字，不要用代码块包裹。"""


def restructure_resume_markdown(llm, raw_markdown: str) -> str:
    """Use LLM to reorganize resume markdown into clean, well-structured markdown.

    Args:
        llm: An LLM service instance (must have a ``chat`` method).
        raw_markdown: The raw/cleaned markdown text from PDF parsing.

    Returns:
        Well-structured markdown text, or the original text on failure.
    """
    if not raw_markdown or not raw_markdown.strip():
        return raw_markdown

    # Skip if text is too short to benefit from restructuring
    if len(raw_markdown) < 100:
        return raw_markdown

    user_prompt = f"请整理以下简历内容：\n\n{raw_markdown}"

    try:
        result = llm.chat(_RESTRUCTURE_SYSTEM_PROMPT, user_prompt, max_tokens=4096, temperature=0.1)
        if result and len(result.strip()) > 50:
            return result.strip()
        return raw_markdown
    except Exception:
        return raw_markdown
